const TrelloActionTypes = {
  // Lists
  POST_SUCCESS_LIST: "POST_SUCCESS_LIST",
  POST_LIST: "POST_LIST",
  DELETE_SUCCESS_LIST: "DELETE_SUCCESS_LIST",
  DELETE_LIST: "DELETE_LIST",
  // Cards
  POST_SUCCESS_CARD: "POST_SUCCESS_CARD",
  POST_CARD: "POST_CARD",
  PATCH_SUCCESS_CARD: "PATCH_SUCCESS_CARD",
  PATCH_CARD: "PATCH_CARD",
  DELETE_SUCCESS_CARD: "DELETE_SUCCESS_CARD",
  DELETE_CARD: "DELETE_CARD",
  // Others
  REMOVE_SUCCESS_CODE: "REMOVE_SUCCESS_CODE",
  REMOVE_WARNING_CODE: "REMOVE_WARNING_CODE",
  REMOVE_FAIL_CODE: "REMOVE_FAIL_CODE",
  SET_SUCCESS_CODE: "SET_SUCCESS_CODE",
  SET_WARNING_CODE: "SET_WARNING_CODE",
  SET_FAIL_CODE: "SET_FAIL_CODE",
  RESET_DATA: "RESET_DATA",
}

export default TrelloActionTypes
