const TrelloActionTypes = {
  POST_SUCCESS_LIST: "POST_SUCCESS_LIST",
  POST_LIST: "POST_LIST",
  DELETE_SUCCESS_LIST: "DELETE_SUCCESS_LIST",
  DELETE_LIST: "DELETE_LIST",
  RESET_DATA: "RESET_DATA",
  // CODE
  REMOVE_SUCCESS_CODE: "REMOVE_SUCCESS_CODE",
  REMOVE_WARNING_CODE: "REMOVE_WARNING_CODE",
  REMOVE_FAIL_CODE: "REMOVE_FAIL_CODE",
  SET_SUCCESS_CODE: "SET_SUCCESS_CODE",
  SET_WARNING_CODE: "SET_WARNING_CODE",
  SET_FAIL_CODE: "SET_FAIL_CODE",
}

export default TrelloActionTypes
