const TrelloActionTypes = {
  POST_SUCCESS_LIST: "POST_SUCCESS_LIST",
  POST_LIST: "POST_LIST",
  SET_SUCCESS_CODE: "SET_SUCCESS_CODE",
  SET_WARNING_CODE: "SET_WARNING_CODE",
  SET_FAIL_CODE: "SET_FAIL_CODE",
}

export default TrelloActionTypes
